_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
uav:
    value:
        range: 3000
        speed: 3
        swapping_time: 2
ugv:
    value:
        num_primitives: 4
        range: 10000000
world:
    value:
        bms: false
        cell_size: 50
        max_timesteps: 1000
        maze: data/maze.csv
        maze_loop_percentage: 60
        maze_size: 10
        num_base_stations: 4
        num_tasks: 5
        num_uavs_per_bs: 2
        num_ugvs: 3
        warehouse: center
