algo: sarsa
policy_name: 9548a1e3
policy_path: runs/sarsa/9548a1e3/policy.pkl
traffic:
  num_centroids: 2
  prob: 0.3
  reset_dur: 5
  std_dev: 1
uav:
  range: 3000
  speed: 3
  swapping_time: 2
ugv:
  drain_rate: 1
  max_load: 100
  num_primitives: 5
  range: 100000000
  speed: 1
world:
  bms: false
  cell_size: 50
  load: false
  max_time: 50000
  maze_file: data/rl_maze.csv
  maze_loop_percentage: 90
  maze_size: 5
  num_base_stations: 4
  num_tasks: 3
  num_uavs_per_bs: 2
  num_ugvs: 1
  traffic: true
  warehouse: center
