world:
  maze: data/maze.csv
  maze_size: 20
  maze_loop_percentage: 60
  cell_size: 50
  
  num_tasks: 10

  warehouse: center
    
  num_base_stations: 4
  num_uavs_per_bs: 2
  num_ugvs: 3

  bms: True
  max_timesteps: 1000

ugv:
  range: 2000
  num_primitives: 4

uav:
  range: 3000
  speed: 3
  swapping_time: 2

# world:
#   maze: data/test_maze.csv
#   num_evs: 1
#   num_tasks: 2
#   num_uavs_per_bs: 2
#   num_base_stations: 4

# ev:
#   range: 3000

# uav:
#   range: 2000
#   speed: 3
