world:
  maze_file: data/rl_maze.csv
  maze_size: 5
  maze_loop_percentage: 90
  cell_size: 50
  
  num_tasks: 3

  warehouse: center
    
  num_base_stations: 4
  num_uavs_per_bs: 2
  num_ugvs: 1

  bms: false
  traffic: true
  load: false
  max_time: 50000

ugv:
  range: 100000000
  drain_rate: 1
  num_primitives: 5
  max_load: 100
  speed: 1

uav:
  range: 3000
  speed: 3
  swapping_time: 2

traffic:
  std_dev: 1
  reset_dur: 5
  prob: 0.3
  num_centroids: 2
  