maze:
  maze_size: 5
  maze_loop_percentage: 60
  cell_size: 50
  warehouse: center
  num_base_stations: 4

task:
  num_tasks: 5000
  task_prob: 0.8

fleet:  
  ugv:
    count: 5
    range: 2000
    drain_rate: 1
    num_primitives: 5
    speed: 1
  uav:
    range: 3000
    speed: 3
    swapping_time: 2
    num_uavs_per_bs: 2

traffic:
  delay_factor: 10
  std_dev: 1
  reset_dur: 5
  prob: 0.7
  num_centroids: 2

simulation:
  max_time: 50000
  bms: false
  traffic: true
  algo: "dijkstra"
  render_mode: "human"
  train: false

training:
  sarsa:
    num_episodes: 50000
    gamma: 0.99
    alpha: 0.1
    epsilon: 0.2
    epsilon_decay: 0.999
