world:
  maze: data/maze.csv
  num_evs: 3
  num_tasks: 5
  num_uavs_per_bs: 2
  num_base_stations: 4
  maze_loop_percentage: 10
  maze_size: 10

ev:
  range: 30000

uav:
  range: 3000
  speed: 3

# world:
#   maze: data/test_maze.csv
#   num_evs: 1
#   num_tasks: 2
#   num_uavs_per_bs: 2
#   num_base_stations: 4

# ev:
#   range: 3000

# uav:
#   range: 2000
#   speed: 3
