_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        OrderedDict({'battery_levels': array([[10000000., 10000000., 10000000.],
               [10000000., 10000000., 10000000.],
               [10000000., 10000000., 10000000.],
               [10000000., 10000000., 10000000.]], dtype=float32), 'task_positions': array([[ 9,  7,  1,  1,  4, 10,  4,  1, 10,  8],
               [ 3,  4, 10, 10,  6,  7,  7,  6,  7,  3],
               [ 5,  6,  3,  8,  2,  6, 10,  9, 10,  6],
               [ 8,  3,  9, 10,  3,  8,  2,  5,  7,  8]]), 'ugv_positions': array([[5, 5, 5, 5, 5, 5],
               [5, 5, 5, 5, 5, 5],
               [5, 5, 5, 5, 5, 5],
               [5, 5, 5, 5, 5, 5]])})
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7328b5b98410>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 1
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: MultiDiscrete([5 5 5])
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x732887182fc0>
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x73291e97dc70>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x73291e78fec0>
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: 'Dict(''battery_levels'': Box(0.0, 10000000.0, (3,), float32), ''task_positions'': MultiDiscrete([11 11 11 11 11 11 11 11 11 11]), ''ugv_positions'': MultiDiscrete([11 11 11 11 11 11]))'
policy:
    value: |-
        MultiInputActorCriticPolicy(
          (features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (battery_levels): Flatten(start_dim=1, end_dim=-1)
              (task_positions): Flatten(start_dim=1, end_dim=-1)
              (ugv_positions): Flatten(start_dim=1, end_dim=-1)
            )
          )
          (pi_features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (battery_levels): Flatten(start_dim=1, end_dim=-1)
              (task_positions): Flatten(start_dim=1, end_dim=-1)
              (ugv_positions): Flatten(start_dim=1, end_dim=-1)
            )
          )
          (vf_features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (battery_levels): Flatten(start_dim=1, end_dim=-1)
              (task_positions): Flatten(start_dim=1, end_dim=-1)
              (ugv_positions): Flatten(start_dim=1, end_dim=-1)
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=179, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=179, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=15, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.MultiInputActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.DictRolloutBuffer object at 0x73291e876180>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.DictRolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1743972790412994940
target_kl:
    value: None
tensorboard_log:
    value: runs/67yw9feg
uav:
    value:
        range: 3000
        speed: 3
        swapping_time: 2
ugv:
    value:
        num_primitives: 4
        range: 10000000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
world:
    value:
        bms: false
        cell_size: 50
        max_timesteps: 1000
        maze: data/maze.csv
        maze_loop_percentage: 60
        maze_size: 10
        num_base_stations: 4
        num_tasks: 5
        num_uavs_per_bs: 2
        num_ugvs: 3
        warehouse: center
