fleet:
  uav:
    num_uavs_per_bs: 2
    range: 1500
    speed: 3
    swapping_time: 2
  ugv:
    count: 1
    drain_rate: 1
    num_primitives: 5
    range: 3000
    speed: 1
maze:
  cell_size: 50
  maze_loop_percentage: 60
  maze_size: 5
  num_base_stations: 4
  warehouse: center
policy_name: f9703824
simulation:
  algo: sarsa
  bms: false
  max_time: 50000
  render_mode: print
  traffic: true
  train: 'false'
task:
  num_tasks: 5000
  task_prob: 0.8
traffic:
  delay_factor: 10
  num_centroids: 2
  prob: 0.7
  reset_dur: 5
  std_dev: 1
training:
  sarsa:
    alpha: 0.1
    epsilon: 0.2
    epsilon_decay: 0.999
    gamma: 0.99
    num_episodes: 50000
